import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
        <nav className="flex justify-center  border-2">
          <ul className="flex gap-3 items-center justify-around w-full">
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/posts"}>posts</Link>
            </li>
            <li>
              <Link href={"/posts/new"}>Create a new post</Link>
            </li>
            <li>
              <Link href={"/user"}>Profile</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
